events {}

http {
  server {
    listen 80;
    server_name _;

    location / {
      proxy_pass http://workspace:3000;
    }

    location /oauth/ {
      proxy_pass http://workspace:8080/;
    }

    location /api/ {
      proxy_pass http://workspace:8081/;
    }
  }
}
